# 0) Importing the right tools <font color='blue'> (5 min) </font>

### <font color='red'>0.1) Import the necessary packages with their usual aliases: </font>

- pandas as pd
- numpy as np
- seaborn as sns
- matplotlib.pyplot as plt

In [1]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
%cd /content/drive/My Drive/dataset_gclass
!ls

Mounted at /content/drive
/content/drive/My Drive/dataset_gclass
 201507-citibike-tripdata.csv	     'input_data_for_modeling_purpose (1).csv'
 201508-citibike-tripdata.csv	      logisticregression.pkl
 data_after_feature_engineering.csv   randomforest.pkl


In [2]:
from __future__ import division
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

#### IMPORT THE USUAL PACKAGES WITH THEIR ALIASES ####

import warnings
warnings.filterwarnings('ignore')

%pylab inline

Populating the interactive namespace from numpy and matplotlib


### <font color='red'>0.2) Import the dataset from <i>'../data/input_data_for_modeling_purpose.csv'</i></font>

In [4]:
raw_data = pd.read_csv('input_data_for_modeling_purpose (1).csv')
#### IMPORT AND READ THE CSV DATA USING pd.read_csv() #### 

### <font color='red'>0.3) Copy the raw_data, print samples, and prepare features & labels for training & testing</font>

In [5]:
data = raw_data.copy()
#### COPY THE RAW DATA WITH THE .copy() FUNCTION ####

In [6]:
data.head()
#### PRINT SAMPLES USING .sample() AND CHECK THE FEATURES ####

tripduration  start station latitude  ...  is_circle_trip_0  is_circle_trip_1
0          1338               40.727103  ...                 1                 0
1           290               40.727791  ...                 1                 0
2           634               40.735238  ...                 1                 0
3           159               40.716059  ...                 1                 0
4          1233               40.734927  ...                 1                 0

[5 rows x 24 columns]

In [7]:
data.shape

(935588, 24)

In [8]:
labels = np.array(data.usertype)
del data['usertype']
features = np.array(data)

In [9]:
import sklearn
from sklearn.preprocessing import label_binarize
binarized_labels = label_binarize(labels, classes=['Customer', 'Subscriber']).ravel() 
#### BINARIZE THE LABELS OF THE DATASET, AND RAVEL THE RESULT USING .ravel() ####
                   #### Subscriber will be label 1, Customer label 0 ####
                   #### This will be a binary classifiation problem ####

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, binarized_labels, test_size=0.3, random_state = 27)
#### SPLIT BETWEEN TRAIN AND TEST ####

# 1) Model Selection <font color='blue'> (40 min) </font>

In [11]:
!pip install -U scikit-learn

### <font color='red'>1.1) Logistic Regression </font>

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
lr = LogisticRegression()
score = cross_val_score(lr, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Logistic Regression Average Score: ', score.mean())

[0.81987693 0.81759128 0.81626884]
Logistic Regression Average Score:  0.8179123479345535


### <font color='red'>1.2) Nearest Neighbors </font>

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
score = cross_val_score(knn, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('KNN Average Score: ', score.mean())

[0.73499312 0.73709919 0.73326569]
KNN Average Score:  0.735119333721233


### <font color='red'>1.3) Gaussian Naive Bayes </font>

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
score = cross_val_score(nb, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Naive Bayes Average Score: ', score.mean())

[0.77463431 0.77148516 0.77332766]
Naive Bayes Average Score:  0.7731490439211871


### <font color='red'>1.4) Neural Network </font>

In [ ]:
from sklearn.neural_network import MLPClassifier
nn = MLPClassifier(solver='lbfgs', hidden_layer_sizes=(5, 2), random_state=1)
score = cross_val_score(nn, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Neural Network Average Score: ', score.mean())

[0.5 0.5 0.5]
Neural Network Average Score:  0.5


### <font color='red'>1.5) Decision Tree </font>

In [ ]:
from sklearn import tree
dt = tree.DecisionTreeClassifier()
score = cross_val_score(dt, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Decision Tree Average Score: ', score.mean())

[0.69177409 0.69372959 0.69505664]
Decision Tree Average Score:  0.693520104837015


### <font color='red'>1.6) Random Forest </font>

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 10)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

[0.8284556  0.83002625 0.82745228]
Random Forest Average Score:  0.8286447112061053


# 2) Hyperparameter Tuning <font color='blue'> (45 min) </font>

### <font color='red'>2.1) Please use help function to have a better understanding about RandomForestClassifier and hyperparameters that can be tuned </font>

In [ ]:
help(RandomForestClassifier)

Help on class RandomForestClassifier in module sklearn.ensemble._forest:

class RandomForestClassifier(ForestClassifier)
 |  RandomForestClassifier(n_estimators=100, *, criterion='gini', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, min_impurity_decrease=0.0, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None)
 |  
 |  A random forest classifier.
 |  
 |  A random forest is a meta estimator that fits a number of decision tree
 |  classifiers on various sub-samples of the dataset and uses averaging to
 |  improve the predictive accuracy and control over-fitting.
 |  The sub-sample size is controlled with the `max_samples` parameter if
 |  `bootstrap=True` (default), otherwise the whole dataset is used to build
 |  each tree.
 |  
 |  Read more in the :ref:`User Guide <forest>`.
 |  
 |  Parameters
 |  ----------


### <font color='red'>2.1) Please try to change several hyperparameters in RandomForestClassifier to improve model performance </font>

#### n_estimators

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 20)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

[0.84760944 0.84994734 0.8445711 ]
Random Forest Average Score:  0.8473759602448955


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 50)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

[0.86028383 0.86093888 0.85798672]
Random Forest Average Score:  0.8597364763860255


#### max_depth

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 50, max_depth = 10)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

[0.84109412 0.83903832 0.83733086]
Random Forest Average Score:  0.8391544361231019


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 50, max_depth = 20)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

[0.86253749 0.86231759 0.86010393]
Random Forest Average Score:  0.861653006727296


#### max_features

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 50, max_depth = 20, max_features = 5)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

[0.86293286 0.86346103 0.86091553]
Random Forest Average Score:  0.8624364719286058


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 50, max_depth = 20, max_features = 10)
score = cross_val_score(rf, X_train, y_train, scoring='roc_auc', cv=3)
print(score)
print('Random Forest Average Score: ', score.mean())

[0.86312448 0.86263132 0.86036169]
Random Forest Average Score:  0.8620391651920057


In [ ]:
rf.fit(X_train, y_train) # fit the final model

RandomForestClassifier(max_depth=20, max_features=10, n_estimators=50)

### <font color='red'>2.3) Save the final model </font>

In [ ]:
import pickle

In [ ]:
os.getcwd() # << Cek current folder directory

'/content/drive/My Drive/dataset_gclass'

In [ ]:
import os
os.chdir('/content/drive/My Drive/dataset_gclass') # << Ganti directory folder

In [ ]:
# export model as a pickle object
filename = 'randomforest.pkl'
pickle.dump(rf, open(filename, 'wb'))

In [ ]:
filename = 'logisticregression.pkl'
pickle.dump(lr, open(filename, 'wb'))

# 3) Exercise - Please be creative and try to improve model performance <font color='blue'> (20 min) </font>